[package]
name = "keypair_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "1.17.10"
solana-client = "1.17.10"
spl-token-client = "0.10.0"
spl-token-2022 = "3.0.2"
spl-associated-token-account = "3.0.2"
clap = "2.33.0"
solana-remote-wallet = {version = "1.18.17", features = ["hidapi"]}
solana-clap-utils = "1.18.17"

log = "0.4"
simple_logger = "5.0.0"

dotenv = "0.15.0" 
serde_json = "1.0.1"
tokio = { version = "1", features = ["full"] }